### ISSUE TITLE
The current example will get fired on new branches as well not only new tags

### ISSUE THREAD

**Issue by arvvoid** [xbmc/action-kodi-addon-submitter#4]
I recently migrated to GitHub Action for CI and in experimenting and testing I found out that

```
on:
  create:
    tags:
      - v*
```

Will not get fired only on new tags but also every time a new branch is created on the repository, so having only that like in the example will generate unintended releases when creating a new branch.
It works as intended on pushing a new tag.

I solved the issue for now with adding an additional safeguard on the jobs in the workflow:

`if: startsWith(github.ref, 'refs/tags/') && github.actor == 'arvvoid'`

(The github actor part is to prevent release publishing jobs to run unintentionally on forks)

This way the jobs inside the workflow run on a new tag but get skipped if it fired up because of a create branch.

Example of my publish workflow: https://github.com/arvvoid/plugin.video.hbogoeu/blob/master/.github/workflows/publish.yml

It would be useful to update the documentation and example with this info. 
I will see if there is a better way to make it fire the workflow only on new tags as well, but that additional safeguard does the job for now.

@enen92

**Comment by arvvoid** [comment]
For clarity current examples in readme should be:

```
name: Kodi Addon-Submitter

on:
  create:
    tags:
      - v*

jobs:
  kodi-addon-submitter:
    if: startsWith(github.ref, 'refs/tags/')  # prevent from running if it's not a tag
    runs-on: ubuntu-latest
    name: Kodi addon submitter
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate distribution zip and submit to official kodi repository
      id: kodi-addon-submitter
      uses: xbmc/action-kodi-addon-submitter@v1.1
      with: # Replace all the below variables
        kodi-repository: repo-plugins
        kodi-version: leia
        addon-id: plugin.video.example
        kodi-matrix: false # Submit a Python 2/3 compatible addon to matrix branch in addition to the target branch
      env: # Make sure you create the below secrets (GH_TOKEN and EMAIL)
        GH_USERNAME: ${{ github.actor }}
        GH_TOKEN: ${{secrets.GH_TOKEN}}
        EMAIL: ${{secrets.EMAIL}}
```

With release:

```
name: Kodi Addon-Submitter

on:
  create:
    tags:
      - v*

jobs:
  kodi-addon-submitter:
    if: startsWith(github.ref, 'refs/tags/')  # prevent from running if it's not a tag
    runs-on: ubuntu-latest
    name: Kodi addon submitter
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate distribution zip and submit to official kodi repository
      id: kodi-addon-submitter
      uses: xbmc/action-kodi-addon-submitter@v1.1
      with: # Replace all the below values
        kodi-repository: repo-plugins
        kodi-version: leia
        addon-id: plugin.video.example
        kodi-matrix: false # Submit a Python 2/3 compatible addon to matrix branch in addition to the target branch
      env: # Make sure you create the below secrets (GH_TOKEN and EMAIL)
        GH_USERNAME: ${{ github.actor }}
        GH_TOKEN: ${{secrets.GH_TOKEN}}
        EMAIL: ${{secrets.EMAIL}}
    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Addon zip to github release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.kodi-addon-submitter.outputs.addon-zip }}
        asset_name: ${{ steps.kodi-addon-submitter.outputs.addon-zip }}
        asset_content_type: application/zip
```

For Py2/3 compatible add-on with release:

```
name: Kodi Addon-Submitter

on:
  create:
    tags:
      - v*

jobs:
  kodi-addon-submitter:
    if: startsWith(github.ref, 'refs/tags/')  # prevent from running if it's not a tag
    runs-on: ubuntu-latest
    name: Kodi addon submitter
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Generate distribution zip and submit to official kodi repository
      id: kodi-addon-submitter
      uses: xbmc/action-kodi-addon-submitter@v1.1
      with: # Replace all the below values
        kodi-repository: repo-plugins
        kodi-version: leia
        addon-id: plugin.video.example
        kodi-matrix: true # Submit a Python 2/3 compatible addon to matrix branch in addition to the target branch
      env: # Make sure you create the below secrets (GH_TOKEN and EMAIL)
        GH_USERNAME: ${{ github.actor }}
        GH_TOKEN: ${{secrets.GH_TOKEN}}
        EMAIL: ${{secrets.EMAIL}}
    - name: Create Github Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Addon zip for Leia to github release
      id: upload-release-asset-leia
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.kodi-addon-submitter.outputs.addon-zip }}
        asset_name: ${{ steps.kodi-addon-submitter.outputs.addon-zip }}
        asset_content_type: application/zip
    - name: Upload Addon zip for Matrix to github release
      id: upload-release-asset-matrix
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.kodi-addon-submitter.outputs.addon-zip-matrix }}
        asset_name: ${{ steps.kodi-addon-submitter.outputs.addon-zip-matrix }}
        asset_content_type: application/zip
```

**Comment by TobiX** [comment]
According to the discussion in https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075, the `create` event has no `tags` parameter, so the correct event is
```yaml
on:
  push:
    tags:
      - '*'
```
(See for example the post https://github.community/t/how-to-run-github-actions-workflow-only-for-new-tags/16075/24 in that thread)
